DESIGN=top
DESDIR=C:\Users\Public\Documents\Libero\Solution - Copy\Libero_Project\designer\top
TARGET_DIR=C:\Users\Public\Documents\Libero\Solution - Copy\Libero_Project\designer\top
FAM=PolarFire
DIE=PA5M300TS
PACKAGE=fcg1152
PINRPT_BY_NAME=1
PINRPT_BY_NUMBER=1
PINRPT_BOARDLAYOUT=1
BANK_REPORT=1
IOREG_REPORT=1
